### ISSUE TITLE
Self-Host: UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ip' of undefined

### ISSUE THREAD

**Issue by vincent-changqiao** [PawanOsman/ChatGPT#13]
I started the proxy on my machine, but it failed to forward request, and always, the error information is: 

 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ip' of undefined
    at rateLimitMiddleware (file:///root/ChatGPT/middlewares.js:13:160)
    at Layer.handle [as handle_request] (/root/ChatGPT/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/ChatGPT/node_modules/express/lib/router/index.js:328:13)
    at /root/ChatGPT/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/root/ChatGPT/node_modules/express/lib/router/index.js:346:12)
    at next (/root/ChatGPT/node_modules/express/lib/router/index.js:280:10)
    at corsMiddleware (file:///root/ChatGPT/middlewares.js:9:5)
    at Layer.handle [as handle_request] (/root/ChatGPT/node_modules/express/lib/router/layer.js:95:5)

How can I solve this issue?

**Comment by gruberdev** [comment]
Probably related to https://github.com/acheong08/ChatGPT/issues/1236.

**Comment by PawanOsman** [comment]
> How can I solve this issue?

Fixed.



> Probably related to [acheong08/ChatGPT#1236](https://github.com/acheong08/ChatGPT/issues/1236).

No, our reverse proxy is for the official API, and our unofficial reverse proxy API also working fine
