### ISSUE TITLE
The "file" argument must be of type string

### ISSUE THREAD

**Issue by BlackusPL** [PawanOsman/ChatGPT#95]
Can't run newest version on termux
`node:child_process:548                                   validateString(file, 'file');                          ^                                                                                                           TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null                       at normalizeSpawnArguments (node:child_process:548:3)
    at spawn (node:child_process:754:13)                   at file:///data/data/com.termux/files/home/ChatGPT/dist/app.js:321:23
    at new Promise (<anonymous>)
    at StartCloudflaredTunnel (file:///data/data/com.termux/files/home/ChatGPT/dist/app.js:320:12)
    at Server.<anonymous> (file:///data/data/com.termux/files/home/ChatGPT/dist/app.js:351:27)                    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {                             code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v21.6.2`

**Comment by jeffery9** [comment]
add config `CLOUDFLARED=false`  in `.env`
